version: "3.7"

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  default:
    name: "sample_application"

services:

  sample-application-postgres:
    container_name: sample_application_postgres
    image: postgres:12-alpine
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: sample-application
      POSTGRES_PASSWORD: sample-application
      POSTGRES_DB: sample-application
      PGDATA: /var/lib/postgresql/data/sample-application/pgdata

  sample-application-prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus/sample
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    restart: always

  sample-application-grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana/sample-application
    restart: always